menu:
  首页: /blog
  归档: /blog/archives
  关于: /blog/about


widgets:
- search
- category
- tagcloud

excerpt_link: 阅读全文

plugins:
- hexo-generator-feed

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: 
rss: 

favicon: /blog/favicon.ico